src/components/weeklyforecast/weeklyforecast.css
src/components/weeklyforecast/weeklyforecast.html

[feat] 주간 예보 UI구현

---

.prettierrc
package-lock.json
package.json
src/components/playlist/playlist.css
src/components/playlist/playlist.html
src/components/playlist/playlist.js

-플레이리스트 추천 UI HTML, CSS 완료
- #2 
- 플레이리스트 컴포넌트 구현
- 스포티파이 dependencies 추가
- 특이사항 없음

[feat] 플레이리스트 추천 UI 구현

---

src/components/currentWeather/currentWeather.css
src/components/currentWeather/currentWeather.js

-기존 input, lists에 이벤트 등록한 코드 변경

[refactor] Keydownevent 코드 변경

---

index.html
src/components/currentWeather/currentWeather.css
src/components/currentWeather/currentWeather.js
src/styles/main.css

[feat] Component 조립

---

eslint.config.js
package-lock.json
package.json

[chore] ESLint config 추가
- ESLint config 추가
없음.
- ESLint config 설정완료
- js관련 컨벤션 강제
- 참고할 점이나 특이사항 없음

[chore] ESLint config 추가

---

index.html
src/components/currentWeather/currentWeather.html
src/components/currentWeather/currentWeather.js

- 현재시간 time태그 추가
- 검색결과가 없을시 UI 추가

[feat] UI, html 구조 변경

---

src/components/placeRecommand/woohyeun.js

- js코드 오류 (null) 수정
- .
- null 오류 방지를 위해 document.getElementById("theme-toggle") 존재 여부 확인 로직 추가
- .

[refactor] js코드 오류 수정(null)

---

public/data/place.json

- 장소 추천 json 파일 추가
- 날씨 코드에 맞는 장소 추천 데이터

[docs] 장소추천 json파일 추가

---

src/components/placeRecommand/place.json
src/components/placeRecommand/woohyeun.css
src/components/placeRecommand/woohyeun.html
src/components/placeRecommand/woohyeun.js

- 어떤 작업을 했는지 간단히 작성
- #이슈번호 (있다면)
- 주요 변경점 요약
- 참고할 점이나 특이사항

Woohyeun code

---

src/common/_theme.css

[feat] _theme.css 커스텀 프로퍼티 추가

---

index.html
src/common/_theme.css
src/components/currentWeather/currentWeather.css
src/components/currentWeather/currentWeather.html
src/components/placeRecommand/woohyeun.css
src/components/placeRecommand/woohyeun.js
src/js/darkmode.js
src/js/geolocation.js
src/js/main.js
src/styles/main.css

- 다크 모드 수정
- _theme.css에 색상 수정 및 사이즈 단위 rem으로 변경

[refactor] DarkMode 기능 수정

---

index.html
public/data/place.json
src/components/currentWeather/currentWeather.js
src/components/placeRecommand/woohyeun.css
src/components/placeRecommand/woohyeun.js
src/js/main.js

- fetch -> axios로 수정
- main.js에서 데이터를 전달받아 렌더링

[refactor] 장소추천 리팩토링

---

src/components/weeklyforecast/weeklyforecast.css
src/components/weeklyforecast/weeklyforecast.html
src/components/weeklyforecast/weeklyforecast.js
src/js/main.js

[feat] 주간예보 기능 구현

---

index.html
src/components/currentWeather/currentWeather.css
src/components/currentWeather/currentWeather.js

[style] Search Input Outline modify

---

src/components/playlist/playlist.css
src/components/playlist/playlist.js
src/service/kakaoMap.js
src/service/openWeatherMap.js
src/service/spotify.js

[feat] 플레이리스트 날씨 연동
- 플레이리스트 날씨와 연동
#2 
- 플레이리스트ID 가 계속 오류가 발생 
- 스포티파이가 생성한 플레이리스트가 아닌 개인 사용자가 만든 공개 플레이리스트 사용 시 오류 나지 않음!

[feat] 플레이리스트 날씨 연동

---

src/components/mapLocation/map-location.js

- URL 파라미터 id로 동적 장소 로딩 기능 추가
- place.json에서 장소 데이터 자동 검색
- 카카오맵 API로 주소→좌표 변환
- 동적 장소명, 이미지, 날씨 정보 렌더링

feat: 요청 기능 변경 완료

---

src/common/_theme.css
src/components/weeklyforecast/weeklyforecast.css

- 주간예보 다크모드 폰트 색상, bg색상 수정 및 스크롤바 제거

[style] 주간예보 다크모드 폰트 색상, bg색상 수정 및 스크롤바 제거

---

src/components/mapLocation/api_keys.js

security: Remove api_keys.js file with hardcoded API keys

---

index.html
src/components/playlist/playlist.css
src/components/playlist/playlist.js
src/service/spotify.js

- 스포티파이 플레이리스트 앨범 10개씩 가져오게 수정
- 앨범 클릭 시 플레이리스트로 이동
- 플레이리스트 앨범 정렬 수정
- 시멘틱 구조 개선
- #6 
- 스타일, 기능 변경
- 없음

[style] 플레이리스트 스타일 수정

---

src/components/placeRecommand/woohyeun.js

[refactor] 경로 수정

---

src/components/placeRecommand/woohyeun.css

- 탭할때 붉은색 강조선 추가
- 소제목 좌정렬
- 모바일 기능시 내용 짤리지 않게 크기 조정
- 어떤 작업을 했는지 간단히 작성
- #이슈번호 (있다면)
- 주요 변경점 요약
- 참고할 점이나 특이사항

[refactor]

---

src/components/placeRecommand/woohyeun.css

- 어떤 작업을 했는지 간단히 작성
- #이슈번호 (있다면)
- 주요 변경점 요약
- 참고할 점이나 특이사항

[refactor] - carousel min-width 삭제

---

index.html
src/components/currentWeather/currentWeather.css
src/components/currentWeather/currentWeather.html
src/components/currentWeather/currentWeather.js
src/components/placeRecommand/woohyeun.css

UI 수정후 배포 테스트

---

index.html
netlify.toml
netlify/functions/getSpotifyTokens.js
src/components/playlist/playlist.css
src/components/playlist/playlist.html
src/components/playlist/playlist.js
src/components/playlist/playlist__carousel.js
src/js/main.js

- 플레이리스트 부분 화살표 버튼 추가
- spotify secret 보안 업데이트
- #이슈번호 (있다면)
- 화살표 버튼으로 접근성 향상
- 보안업데이트로 secret 값 노출 최소화
-

[Feature] 화살표버튼 추가 및 보안 업데이트

---

.gitignore
index.html
src/components/playlist/playlist.html
src/components/playlist/playlist.js
src/components/playlist/playlist__carousel.js
src/js/main.js
src/service/spotify.js

플레이리스트 에러 처리 및 접근성 개선
- 플레이리스트 에러 처리 및 접근성 개선
- #이슈번호 (있다면)
- 날씨 데이터, Spotify 인증/토큰, 트랙 불러오기 실패 시
alert로 사용자에게 즉시 피드백 제공
-스크린 리더 사용자를 위한 aria-label 속성 추가
-앨범 커버 없는 경우에도 오류 방지를 위해 빈 문자열 처리
-사용자 알림 메시지 문구 수정 (더 자연스러운 문장으로 개선)
-오타 수정
- 없음

[feat] 플레이리스트 에러 처리 및 접근성 개선

---

index.html
src/common/_theme.css
src/components/currentWeather/currentWeather.js
src/components/modal/modal.css
src/components/modal/modal.html
src/components/placeRecommand/woohyeun.css
src/components/placeRecommand/woohyeun.js
src/components/playlist/playlist.js
src/js/geolocation.js
src/js/getWeatherData.js
src/js/utils.js
src/service/spotify.js
src/styles/main.css

Feat/error modal/youngju

---

index.html
src/components/weeklyforecast/weeklyforecast.js

- 주간 예보 img 태그 동적 생성으로 변경
- 헤더 time tag 필수 값 추가
- #77 
- 주간 예보 img 태그 변경으로 초기 오류 수정
- 헤더 time tag 필수 값 추가
- 없음

[refactor] 주간예보 img 태그 동적 생성으로 변경

---

public/mock-data/forecast-data.js
public/mock-data/weather-data.js
src/components/weeklyforecast/weeklyforecast.js
src/js/darkmode.js
src/js/utils.js
src/lib/axios.js

코드 스타일 정리 및 불필요한 콘솔로그 제거
- eslint 자동 수정 적용
- 불필요한 콘솔 로그 제거, 주석처리
- #77 
- 큰 변경 없음
- 참고할 점이나 특이사항 없음

[chore] 코드 스타일 정리 및 불필요한 콘솔로그 제거

---

src/components/playlist/playlist.js
src/js/main.js

[feat] 플레이리스트 타이틀 수정
- 현재 지역정보도 같이 렌더링되게 수정
- #61 
- 현재 지역정보도 타이틀에 같이 렌더링 되게 수정
- 날씨 정보 받아오는 main 함수에서 위치정보도 같이 받아옴 
- 없음

[feat] 플레이리스트 타이틀 수정

---

netlify/functions/getSpotifyTokens.js
src/service/spotify.js

- 어떤 작업을 했는지 간단히 작성
- #이슈번호 (있다면)
- 주요 변경점 요약
- 참고할 점이나 특이사항

[fix] 플레이리스트 오류 처리
